generateFormattingScript <- function(name, formatting_actions) {
  script <- paste0("#### SCRIPT GENERATED BY FeatureEngineeR ####\n\n\n",
                   paste0(sapply(formatting_actions, generateFormattingTidbit, name),
                          collapse = "\n\n"))
  
  script
}

generateFormattingTidbit <- function(formatting_action, name) {
  script <- paste0("#### Formatting: ", formatting_action$initial_name, "\n")
  
  if (!identical(formatting_action$initial_name, formatting_action$new_name)) {
    script <- paste0(script, "\n# Renaming ", formatting_action$initial_name, " to ", formatting_action$new_name)
    script <- paste0(script, "\ncolnames(", name, ")[colnames(", name, ") == ", formatting_action$initial_name, '] <- "', formatting_action$new_name, '"')
  }
  
  
  
  script
}